// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: swarm.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coupling int32

const (
	Coupling_COUPLING_INDEPENDENT     Coupling = 0
	Coupling_COUPLING_BARRIER         Coupling = 1
	Coupling_COUPLING_LEADER          Coupling = 2
	Coupling_COUPLING_MESSAGE_PASSING Coupling = 3
)

// Enum value maps for Coupling.
var (
	Coupling_name = map[int32]string{
		0: "COUPLING_INDEPENDENT",
		1: "COUPLING_BARRIER",
		2: "COUPLING_LEADER",
		3: "COUPLING_MESSAGE_PASSING",
	}
	Coupling_value = map[string]int32{
		"COUPLING_INDEPENDENT":     0,
		"COUPLING_BARRIER":         1,
		"COUPLING_LEADER":          2,
		"COUPLING_MESSAGE_PASSING": 3,
	}
)

func (x Coupling) Enum() *Coupling {
	p := new(Coupling)
	*p = x
	return p
}

func (x Coupling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Coupling) Descriptor() protoreflect.EnumDescriptor {
	return file_swarm_proto_enumTypes[0].Descriptor()
}

func (Coupling) Type() protoreflect.EnumType {
	return &file_swarm_proto_enumTypes[0]
}

func (x Coupling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Coupling.Descriptor instead.
func (Coupling) EnumDescriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

// Health mirrors model.Health ordinals verbatim (Healthy=0, Degraded=1,
// Unreachable=2).
type Health int32

const (
	Health_HEALTH_HEALTHY     Health = 0
	Health_HEALTH_DEGRADED    Health = 1
	Health_HEALTH_UNREACHABLE Health = 2
)

// Enum value maps for Health.
var (
	Health_name = map[int32]string{
		0: "HEALTH_HEALTHY",
		1: "HEALTH_DEGRADED",
		2: "HEALTH_UNREACHABLE",
	}
	Health_value = map[string]int32{
		"HEALTH_HEALTHY":     0,
		"HEALTH_DEGRADED":    1,
		"HEALTH_UNREACHABLE": 2,
	}
)

func (x Health) Enum() *Health {
	p := new(Health)
	*p = x
	return p
}

func (x Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Health) Descriptor() protoreflect.EnumDescriptor {
	return file_swarm_proto_enumTypes[1].Descriptor()
}

func (Health) Type() protoreflect.EnumType {
	return &file_swarm_proto_enumTypes[1]
}

func (x Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Health.Descriptor instead.
func (Health) EnumDescriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{1}
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Coupling      Coupling               `protobuf:"varint,2,opt,name=coupling,proto3,enum=swarm.v1.Coupling" json:"coupling,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SubmitJobRequest) GetCoupling() Coupling {
	if x != nil {
		return x.Coupling
	}
	return Coupling_COUPLING_INDEPENDENT
}

func (x *SubmitJobRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// JoinAgentRequest: raft_addr and cell_leader_addr are the agent's two P2
// listeners, advertised so a coupled cell can form its raft cluster and the
// elected leader can reach it. Both empty for a P0/P1 agent that never joins a
// coupled cell — existing JoinAgent behavior is unchanged.
type JoinAgentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Agent          string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Region         string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Caps           int32                  `protobuf:"varint,3,opt,name=caps,proto3" json:"caps,omitempty"`
	RaftAddr       string                 `protobuf:"bytes,4,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`                     // TCP address this agent's raft NetworkTransport advertises
	CellLeaderAddr string                 `protobuf:"bytes,5,opt,name=cell_leader_addr,json=cellLeaderAddr,proto3" json:"cell_leader_addr,omitempty"` // this agent's CellLeader gRPC address
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinAgentRequest) Reset() {
	*x = JoinAgentRequest{}
	mi := &file_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAgentRequest) ProtoMessage() {}

func (x *JoinAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAgentRequest.ProtoReflect.Descriptor instead.
func (*JoinAgentRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *JoinAgentRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *JoinAgentRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *JoinAgentRequest) GetCaps() int32 {
	if x != nil {
		return x.Caps
	}
	return 0
}

func (x *JoinAgentRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *JoinAgentRequest) GetCellLeaderAddr() string {
	if x != nil {
		return x.CellLeaderAddr
	}
	return ""
}

type JoinAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAgentResponse) Reset() {
	*x = JoinAgentResponse{}
	mi := &file_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAgentResponse) ProtoMessage() {}

func (x *JoinAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAgentResponse.ProtoReflect.Descriptor instead.
func (*JoinAgentResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *JoinAgentResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *JoinAgentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinAgentResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CellAssignmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellAssignmentRequest) Reset() {
	*x = CellAssignmentRequest{}
	mi := &file_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellAssignmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellAssignmentRequest) ProtoMessage() {}

func (x *CellAssignmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellAssignmentRequest.ProtoReflect.Descriptor instead.
func (*CellAssignmentRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *CellAssignmentRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

// CellPeer is one voter in a coupled cell's raft cluster.
type CellPeer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RaftAddr       string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	CellLeaderAddr string                 `protobuf:"bytes,3,opt,name=cell_leader_addr,json=cellLeaderAddr,proto3" json:"cell_leader_addr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CellPeer) Reset() {
	*x = CellPeer{}
	mi := &file_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellPeer) ProtoMessage() {}

func (x *CellPeer) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellPeer.ProtoReflect.Descriptor instead.
func (*CellPeer) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *CellPeer) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CellPeer) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

func (x *CellPeer) GetCellLeaderAddr() string {
	if x != nil {
		return x.CellLeaderAddr
	}
	return ""
}

// CellAssignmentResponse tells an agent whether it belongs to a coupled cell
// and, if so, everything it needs to join the raft cluster and compute its
// barrier shard. has_assignment=false => behave as a plain P0/P1 agent.
type CellAssignmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasAssignment bool                   `protobuf:"varint,1,opt,name=has_assignment,json=hasAssignment,proto3" json:"has_assignment,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`        // this agent's barrier WorkerID / member id
	ShardInput    []byte                 `protobuf:"bytes,4,opt,name=shard_input,json=shardInput,proto3" json:"shard_input,omitempty"`  // this worker's DistTrainingDecompose Task.Input
	K             int32                  `protobuf:"varint,5,opt,name=k,proto3" json:"k,omitempty"`                                     // checkpoint cadence
	MinMembers    int32                  `protobuf:"varint,6,opt,name=min_members,json=minMembers,proto3" json:"min_members,omitempty"` // barrier floor
	Steps         int32                  `protobuf:"varint,7,opt,name=steps,proto3" json:"steps,omitempty"`                             // N (completion)
	Bootstrap     bool                   `protobuf:"varint,8,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`                     // exactly one agent per cell bootstraps the raft cluster
	Peers         []*CellPeer            `protobuf:"bytes,9,rep,name=peers,proto3" json:"peers,omitempty"`                              // the full cell voter set (incl. self)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellAssignmentResponse) Reset() {
	*x = CellAssignmentResponse{}
	mi := &file_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellAssignmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellAssignmentResponse) ProtoMessage() {}

func (x *CellAssignmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellAssignmentResponse.ProtoReflect.Descriptor instead.
func (*CellAssignmentResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *CellAssignmentResponse) GetHasAssignment() bool {
	if x != nil {
		return x.HasAssignment
	}
	return false
}

func (x *CellAssignmentResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CellAssignmentResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CellAssignmentResponse) GetShardInput() []byte {
	if x != nil {
		return x.ShardInput
	}
	return nil
}

func (x *CellAssignmentResponse) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *CellAssignmentResponse) GetMinMembers() int32 {
	if x != nil {
		return x.MinMembers
	}
	return 0
}

func (x *CellAssignmentResponse) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *CellAssignmentResponse) GetBootstrap() bool {
	if x != nil {
		return x.Bootstrap
	}
	return false
}

func (x *CellAssignmentResponse) GetPeers() []*CellPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// CellStatusRequest is the elected cell leader's upward status notice. Its
// load-bearing signal is `stalled`: once the hosted barrier parks under the
// min_members floor, the control plane releases + requeues the gang reservation
// so parked capacity isn't stranded. Refill is NOT carried here — the leader
// learns it is runnable again by re-polling CellAssignment (no downward RPC).
type CellStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`       // the gang job id this cell runs (key into gangJobs)
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"` // the reporting leader agent
	Stalled       bool                   `protobuf:"varint,3,opt,name=stalled,proto3" json:"stalled,omitempty"`               // true once the barrier parked under the floor
	Have          int32                  `protobuf:"varint,4,opt,name=have,proto3" json:"have,omitempty"`                     // current surviving membership
	Need          int32                  `protobuf:"varint,5,opt,name=need,proto3" json:"need,omitempty"`                     // min_members floor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellStatusRequest) Reset() {
	*x = CellStatusRequest{}
	mi := &file_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellStatusRequest) ProtoMessage() {}

func (x *CellStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellStatusRequest.ProtoReflect.Descriptor instead.
func (*CellStatusRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *CellStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CellStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CellStatusRequest) GetStalled() bool {
	if x != nil {
		return x.Stalled
	}
	return false
}

func (x *CellStatusRequest) GetHave() int32 {
	if x != nil {
		return x.Have
	}
	return 0
}

func (x *CellStatusRequest) GetNeed() int32 {
	if x != nil {
		return x.Need
	}
	return 0
}

type CellStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellStatusResponse) Reset() {
	*x = CellStatusResponse{}
	mi := &file_swarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellStatusResponse) ProtoMessage() {}

func (x *CellStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellStatusResponse.ProtoReflect.Descriptor instead.
func (*CellStatusResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{8}
}

func (x *CellStatusResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_swarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_swarm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_swarm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{11}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Task) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type PullTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTaskRequest) Reset() {
	*x = PullTaskRequest{}
	mi := &file_swarm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskRequest) ProtoMessage() {}

func (x *PullTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskRequest.ProtoReflect.Descriptor instead.
func (*PullTaskRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{12}
}

func (x *PullTaskRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type PullTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasTask       bool                   `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTaskResponse) Reset() {
	*x = PullTaskResponse{}
	mi := &file_swarm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskResponse) ProtoMessage() {}

func (x *PullTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskResponse.ProtoReflect.Descriptor instead.
func (*PullTaskResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{13}
}

func (x *PullTaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *PullTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_swarm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{14}
}

func (x *ReportResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportResultRequest) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ReportResultRequest) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_swarm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{15}
}

func (x *ReportResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type PsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsRequest) Reset() {
	*x = PsRequest{}
	mi := &file_swarm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsRequest) ProtoMessage() {}

func (x *PsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsRequest.ProtoReflect.Descriptor instead.
func (*PsRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{16}
}

type PsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         int32                  `protobuf:"varint,1,opt,name=cells,proto3" json:"cells,omitempty"`
	Machines      int32                  `protobuf:"varint,2,opt,name=machines,proto3" json:"machines,omitempty"`
	Jobs          int32                  `protobuf:"varint,3,opt,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsResponse) Reset() {
	*x = PsResponse{}
	mi := &file_swarm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsResponse) ProtoMessage() {}

func (x *PsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsResponse.ProtoReflect.Descriptor instead.
func (*PsResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{17}
}

func (x *PsResponse) GetCells() int32 {
	if x != nil {
		return x.Cells
	}
	return 0
}

func (x *PsResponse) GetMachines() int32 {
	if x != nil {
		return x.Machines
	}
	return 0
}

func (x *PsResponse) GetJobs() int32 {
	if x != nil {
		return x.Jobs
	}
	return 0
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_swarm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{18}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Aggregate     []byte                 `protobuf:"bytes,2,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_swarm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{19}
}

func (x *JobStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *JobStatusResponse) GetAggregate() []byte {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

// JobSpec is a job's decomposable spec, carried on cross-region dispatch so a
// region that did not admit the job can still route/aggregate its tasks.
type JobSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	Coupling      Coupling               `protobuf:"varint,3,opt,name=coupling,proto3,enum=swarm.v1.Coupling" json:"coupling,omitempty"`
	Params        map[string]string      `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_swarm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{20}
}

func (x *JobSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobSpec) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *JobSpec) GetCoupling() Coupling {
	if x != nil {
		return x.Coupling
	}
	return Coupling_COUPLING_INDEPENDENT
}

func (x *JobSpec) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// RegionalSummary is what a region publishes upward (mirrors
// routing.RegionalSummary); `at` is the shell-stamped Instant (int64 ns). A
// periodic PublishSummary IS the region heartbeat — a region that stops
// publishing goes stale and is downgraded via routing.Diverged.
type RegionalSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Free          int32                  `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Cells         int32                  `protobuf:"varint,3,opt,name=cells,proto3" json:"cells,omitempty"`
	Health        Health                 `protobuf:"varint,4,opt,name=health,proto3,enum=swarm.v1.Health" json:"health,omitempty"`
	At            int64                  `protobuf:"varint,5,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionalSummary) Reset() {
	*x = RegionalSummary{}
	mi := &file_swarm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionalSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionalSummary) ProtoMessage() {}

func (x *RegionalSummary) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionalSummary.ProtoReflect.Descriptor instead.
func (*RegionalSummary) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{21}
}

func (x *RegionalSummary) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RegionalSummary) GetFree() int32 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *RegionalSummary) GetCells() int32 {
	if x != nil {
		return x.Cells
	}
	return 0
}

func (x *RegionalSummary) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_HEALTHY
}

func (x *RegionalSummary) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

// RegionView is one region as the global layer sees it (mirrors model.RegionView).
type RegionView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Free          int32                  `protobuf:"varint,2,opt,name=free,proto3" json:"free,omitempty"`
	Cells         int32                  `protobuf:"varint,3,opt,name=cells,proto3" json:"cells,omitempty"`
	Health        Health                 `protobuf:"varint,4,opt,name=health,proto3,enum=swarm.v1.Health" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionView) Reset() {
	*x = RegionView{}
	mi := &file_swarm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionView) ProtoMessage() {}

func (x *RegionView) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionView.ProtoReflect.Descriptor instead.
func (*RegionView) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{22}
}

func (x *RegionView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegionView) GetFree() int32 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *RegionView) GetCells() int32 {
	if x != nil {
		return x.Cells
	}
	return 0
}

func (x *RegionView) GetHealth() Health {
	if x != nil {
		return x.Health
	}
	return Health_HEALTH_HEALTHY
}

type PublishSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *RegionalSummary       `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSummaryRequest) Reset() {
	*x = PublishSummaryRequest{}
	mi := &file_swarm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSummaryRequest) ProtoMessage() {}

func (x *PublishSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSummaryRequest.ProtoReflect.Descriptor instead.
func (*PublishSummaryRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{23}
}

func (x *PublishSummaryRequest) GetSummary() *RegionalSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type PublishSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSummaryResponse) Reset() {
	*x = PublishSummaryResponse{}
	mi := &file_swarm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSummaryResponse) ProtoMessage() {}

func (x *PublishSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSummaryResponse.ProtoReflect.Descriptor instead.
func (*PublishSummaryResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{24}
}

func (x *PublishSummaryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GlobalViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalViewRequest) Reset() {
	*x = GlobalViewRequest{}
	mi := &file_swarm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalViewRequest) ProtoMessage() {}

func (x *GlobalViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalViewRequest.ProtoReflect.Descriptor instead.
func (*GlobalViewRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{25}
}

type GlobalViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Regions       []*RegionView          `protobuf:"bytes,1,rep,name=regions,proto3" json:"regions,omitempty"`   // merged, health as of the reply
	Diverged      []string               `protobuf:"bytes,2,rep,name=diverged,proto3" json:"diverged,omitempty"` // RegionIDs routing.Diverged flagged stale
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalViewResponse) Reset() {
	*x = GlobalViewResponse{}
	mi := &file_swarm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalViewResponse) ProtoMessage() {}

func (x *GlobalViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalViewResponse.ProtoReflect.Descriptor instead.
func (*GlobalViewResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{26}
}

func (x *GlobalViewResponse) GetRegions() []*RegionView {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *GlobalViewResponse) GetDiverged() []string {
	if x != nil {
		return x.Diverged
	}
	return nil
}

// DispatchTasksRequest carries global->region (spread) and region->region
// (spill) task delivery. `result_sink` is the dial address that owns roll-up
// for this job: spread -> the global layer (region reports a PARTIAL via
// ReportPartial); spill -> the ORIGIN region (peer reports the raw result via
// the P0 ControlPlane.ReportResult); empty/self -> aggregate locally.
type DispatchTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *JobSpec               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	ResultSink    string                 `protobuf:"bytes,3,opt,name=result_sink,json=resultSink,proto3" json:"result_sink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTasksRequest) Reset() {
	*x = DispatchTasksRequest{}
	mi := &file_swarm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTasksRequest) ProtoMessage() {}

func (x *DispatchTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTasksRequest.ProtoReflect.Descriptor instead.
func (*DispatchTasksRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{27}
}

func (x *DispatchTasksRequest) GetJob() *JobSpec {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *DispatchTasksRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *DispatchTasksRequest) GetResultSink() string {
	if x != nil {
		return x.ResultSink
	}
	return ""
}

type DispatchTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchTasksResponse) Reset() {
	*x = DispatchTasksResponse{}
	mi := &file_swarm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchTasksResponse) ProtoMessage() {}

func (x *DispatchTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchTasksResponse.ProtoReflect.Descriptor instead.
func (*DispatchTasksResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{28}
}

func (x *DispatchTasksResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *DispatchTasksResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// PartialAggregate is a job-level partial reported up the roll-up tree
// (region -> global). `template` is carried because model.Aggregate has no
// template tag and `value` is opaque template-encoded bytes — the receiver
// needs it to call aggregate.Merge. `done` marks the sender's subtree complete.
type PartialAggregate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"` // reporting region (dedup / expected-set tracking)
	Template      string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`
	Value         []byte                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // model.Aggregate.Value
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartialAggregate) Reset() {
	*x = PartialAggregate{}
	mi := &file_swarm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartialAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialAggregate) ProtoMessage() {}

func (x *PartialAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialAggregate.ProtoReflect.Descriptor instead.
func (*PartialAggregate) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{29}
}

func (x *PartialAggregate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PartialAggregate) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PartialAggregate) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *PartialAggregate) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PartialAggregate) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type ReportPartialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partial       *PartialAggregate      `protobuf:"bytes,1,opt,name=partial,proto3" json:"partial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPartialRequest) Reset() {
	*x = ReportPartialRequest{}
	mi := &file_swarm_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPartialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPartialRequest) ProtoMessage() {}

func (x *ReportPartialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPartialRequest.ProtoReflect.Descriptor instead.
func (*ReportPartialRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{30}
}

func (x *ReportPartialRequest) GetPartial() *PartialAggregate {
	if x != nil {
		return x.Partial
	}
	return nil
}

type ReportPartialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPartialResponse) Reset() {
	*x = ReportPartialResponse{}
	mi := &file_swarm_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPartialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPartialResponse) ProtoMessage() {}

func (x *ReportPartialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPartialResponse.ProtoReflect.Descriptor instead.
func (*ReportPartialResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{31}
}

func (x *ReportPartialResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// AssignWork: the cell leader hands a follower its work for a barrier step or a
// leader superstep. `payload` is the driver/template-encoded work shard.
type AssignWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	Step          int32                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"` // barrier step or leader superstep
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWorkRequest) Reset() {
	*x = AssignWorkRequest{}
	mi := &file_swarm_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkRequest) ProtoMessage() {}

func (x *AssignWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkRequest.ProtoReflect.Descriptor instead.
func (*AssignWorkRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{32}
}

func (x *AssignWorkRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssignWorkRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *AssignWorkRequest) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *AssignWorkRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type AssignWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignWorkResponse) Reset() {
	*x = AssignWorkResponse{}
	mi := &file_swarm_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignWorkResponse) ProtoMessage() {}

func (x *AssignWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignWorkResponse.ProtoReflect.Descriptor instead.
func (*AssignWorkResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{33}
}

func (x *AssignWorkResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

// StepReport: a follower reports its result for a step/superstep back to the
// leader — barrier Done{partial} or leader Report{result}. `payload` is the
// partial/result bytes the pure driver folds.
type StepReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	Step          int32                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepReportRequest) Reset() {
	*x = StepReportRequest{}
	mi := &file_swarm_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepReportRequest) ProtoMessage() {}

func (x *StepReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepReportRequest.ProtoReflect.Descriptor instead.
func (*StepReportRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{34}
}

func (x *StepReportRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepReportRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *StepReportRequest) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *StepReportRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StepReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepReportResponse) Reset() {
	*x = StepReportResponse{}
	mi := &file_swarm_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepReportResponse) ProtoMessage() {}

func (x *StepReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepReportResponse.ProtoReflect.Descriptor instead.
func (*StepReportResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{35}
}

func (x *StepReportResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// DeliverMessage: the message-passing driver delivers a Send to an actor's
// mailbox on another node. At-least-once; `message_id` lets the receiver dedupe
// (matches the driver's Seen set).
type DeliverMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ToActor       string                 `protobuf:"bytes,2,opt,name=to_actor,json=toActor,proto3" json:"to_actor,omitempty"`
	MessageId     string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageRequest) Reset() {
	*x = DeliverMessageRequest{}
	mi := &file_swarm_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageRequest) ProtoMessage() {}

func (x *DeliverMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageRequest.ProtoReflect.Descriptor instead.
func (*DeliverMessageRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{36}
}

func (x *DeliverMessageRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DeliverMessageRequest) GetToActor() string {
	if x != nil {
		return x.ToActor
	}
	return ""
}

func (x *DeliverMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliverMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DeliverMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageResponse) Reset() {
	*x = DeliverMessageResponse{}
	mi := &file_swarm_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageResponse) ProtoMessage() {}

func (x *DeliverMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageResponse.ProtoReflect.Descriptor instead.
func (*DeliverMessageResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{37}
}

func (x *DeliverMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// MemberHeartbeat: a follower's liveness ping to its cell leader; feeds
// adaptive-by-tier detection's lastSeen. The leader (not the control plane)
// tracks its own members because it sets the per-step deadlines and evicts
// stragglers. A new RPC is warranted: the P0 ControlPlane.Heartbeat is
// agent->control-plane, a different relationship than member->cell-leader.
type MemberHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberHeartbeatRequest) Reset() {
	*x = MemberHeartbeatRequest{}
	mi := &file_swarm_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberHeartbeatRequest) ProtoMessage() {}

func (x *MemberHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*MemberHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{38}
}

func (x *MemberHeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MemberHeartbeatRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

type MemberHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberHeartbeatResponse) Reset() {
	*x = MemberHeartbeatResponse{}
	mi := &file_swarm_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberHeartbeatResponse) ProtoMessage() {}

func (x *MemberHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*MemberHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{39}
}

func (x *MemberHeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_swarm_proto protoreflect.FileDescriptor

const file_swarm_proto_rawDesc = "" +
	"\n" +
	"\vswarm.proto\x12\bswarm.v1\"\xd9\x01\n" +
	"\x10SubmitJobRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12.\n" +
	"\bcoupling\x18\x02 \x01(\x0e2\x12.swarm.v1.CouplingR\bcoupling\x12>\n" +
	"\x06params\x18\x03 \x03(\v2&.swarm.v1.SubmitJobRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x9b\x01\n" +
	"\x10JoinAgentRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04caps\x18\x03 \x01(\x05R\x04caps\x12\x1b\n" +
	"\traft_addr\x18\x04 \x01(\tR\braftAddr\x12(\n" +
	"\x10cell_leader_addr\x18\x05 \x01(\tR\x0ecellLeaderAddr\"`\n" +
	"\x11JoinAgentResponse\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"-\n" +
	"\x15CellAssignmentRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"l\n" +
	"\bCellPeer\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\x12(\n" +
	"\x10cell_leader_addr\x18\x03 \x01(\tR\x0ecellLeaderAddr\"\xa1\x02\n" +
	"\x16CellAssignmentResponse\x12%\n" +
	"\x0ehas_assignment\x18\x01 \x01(\bR\rhasAssignment\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vshard_input\x18\x04 \x01(\fR\n" +
	"shardInput\x12\f\n" +
	"\x01k\x18\x05 \x01(\x05R\x01k\x12\x1f\n" +
	"\vmin_members\x18\x06 \x01(\x05R\n" +
	"minMembers\x12\x14\n" +
	"\x05steps\x18\a \x01(\x05R\x05steps\x12\x1c\n" +
	"\tbootstrap\x18\b \x01(\bR\tbootstrap\x12(\n" +
	"\x05peers\x18\t \x03(\v2\x12.swarm.v1.CellPeerR\x05peers\"\x87\x01\n" +
	"\x11CellStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\astalled\x18\x03 \x01(\bR\astalled\x12\x12\n" +
	"\x04have\x18\x04 \x01(\x05R\x04have\x12\x12\n" +
	"\x04need\x18\x05 \x01(\x05R\x04need\"0\n" +
	"\x12CellStatusResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"(\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"]\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\"'\n" +
	"\x0fPullTaskRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"Q\n" +
	"\x10PullTaskResponse\x12\x19\n" +
	"\bhas_task\x18\x01 \x01(\bR\ahasTask\x12\"\n" +
	"\x04task\x18\x02 \x01(\v2\x0e.swarm.v1.TaskR\x04task\"V\n" +
	"\x13ReportResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\"2\n" +
	"\x14ReportResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\v\n" +
	"\tPsRequest\"R\n" +
	"\n" +
	"PsResponse\x12\x14\n" +
	"\x05cells\x18\x01 \x01(\x05R\x05cells\x12\x1a\n" +
	"\bmachines\x18\x02 \x01(\x05R\bmachines\x12\x12\n" +
	"\x04jobs\x18\x03 \x01(\x05R\x04jobs\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"E\n" +
	"\x11JobStatusResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x1c\n" +
	"\taggregate\x18\x02 \x01(\fR\taggregate\"\xd7\x01\n" +
	"\aJobSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12.\n" +
	"\bcoupling\x18\x03 \x01(\x0e2\x12.swarm.v1.CouplingR\bcoupling\x125\n" +
	"\x06params\x18\x04 \x03(\v2\x1d.swarm.v1.JobSpec.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0fRegionalSummary\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\x12\x12\n" +
	"\x04free\x18\x02 \x01(\x05R\x04free\x12\x14\n" +
	"\x05cells\x18\x03 \x01(\x05R\x05cells\x12(\n" +
	"\x06health\x18\x04 \x01(\x0e2\x10.swarm.v1.HealthR\x06health\x12\x0e\n" +
	"\x02at\x18\x05 \x01(\x03R\x02at\"p\n" +
	"\n" +
	"RegionView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04free\x18\x02 \x01(\x05R\x04free\x12\x14\n" +
	"\x05cells\x18\x03 \x01(\x05R\x05cells\x12(\n" +
	"\x06health\x18\x04 \x01(\x0e2\x10.swarm.v1.HealthR\x06health\"L\n" +
	"\x15PublishSummaryRequest\x123\n" +
	"\asummary\x18\x01 \x01(\v2\x19.swarm.v1.RegionalSummaryR\asummary\"(\n" +
	"\x16PublishSummaryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x13\n" +
	"\x11GlobalViewRequest\"`\n" +
	"\x12GlobalViewResponse\x12.\n" +
	"\aregions\x18\x01 \x03(\v2\x14.swarm.v1.RegionViewR\aregions\x12\x1a\n" +
	"\bdiverged\x18\x02 \x03(\tR\bdiverged\"\x82\x01\n" +
	"\x14DispatchTasksRequest\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x11.swarm.v1.JobSpecR\x03job\x12$\n" +
	"\x05tasks\x18\x02 \x03(\v2\x0e.swarm.v1.TaskR\x05tasks\x12\x1f\n" +
	"\vresult_sink\x18\x03 \x01(\tR\n" +
	"resultSink\"K\n" +
	"\x15DispatchTasksResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x87\x01\n" +
	"\x10PartialAggregate\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12\x14\n" +
	"\x05value\x18\x04 \x01(\fR\x05value\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"L\n" +
	"\x14ReportPartialRequest\x124\n" +
	"\apartial\x18\x01 \x01(\v2\x1a.swarm.v1.PartialAggregateR\apartial\"'\n" +
	"\x15ReportPartialResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"p\n" +
	"\x11AssignWorkRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"0\n" +
	"\x12AssignWorkResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"p\n" +
	"\x11StepReportRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x05R\x04step\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"$\n" +
	"\x12StepReportResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x82\x01\n" +
	"\x15DeliverMessageRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bto_actor\x18\x02 \x01(\tR\atoActor\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"(\n" +
	"\x16DeliverMessageResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"G\n" +
	"\x16MemberHeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\")\n" +
	"\x17MemberHeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*m\n" +
	"\bCoupling\x12\x18\n" +
	"\x14COUPLING_INDEPENDENT\x10\x00\x12\x14\n" +
	"\x10COUPLING_BARRIER\x10\x01\x12\x13\n" +
	"\x0fCOUPLING_LEADER\x10\x02\x12\x1c\n" +
	"\x18COUPLING_MESSAGE_PASSING\x10\x03*I\n" +
	"\x06Health\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x00\x12\x13\n" +
	"\x0fHEALTH_DEGRADED\x10\x01\x12\x16\n" +
	"\x12HEALTH_UNREACHABLE\x10\x022\xdf\x05\n" +
	"\fControlPlane\x12D\n" +
	"\tSubmitJob\x12\x1a.swarm.v1.SubmitJobRequest\x1a\x1b.swarm.v1.SubmitJobResponse\x12D\n" +
	"\tJoinAgent\x12\x1a.swarm.v1.JoinAgentRequest\x1a\x1b.swarm.v1.JoinAgentResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.swarm.v1.HeartbeatRequest\x1a\x1b.swarm.v1.HeartbeatResponse\x12A\n" +
	"\bPullTask\x12\x19.swarm.v1.PullTaskRequest\x1a\x1a.swarm.v1.PullTaskResponse\x12M\n" +
	"\fReportResult\x12\x1d.swarm.v1.ReportResultRequest\x1a\x1e.swarm.v1.ReportResultResponse\x12/\n" +
	"\x02Ps\x12\x13.swarm.v1.PsRequest\x1a\x14.swarm.v1.PsResponse\x12D\n" +
	"\tJobStatus\x12\x1a.swarm.v1.JobStatusRequest\x1a\x1b.swarm.v1.JobStatusResponse\x12P\n" +
	"\rDispatchTasks\x12\x1e.swarm.v1.DispatchTasksRequest\x1a\x1f.swarm.v1.DispatchTasksResponse\x12S\n" +
	"\x0eCellAssignment\x12\x1f.swarm.v1.CellAssignmentRequest\x1a .swarm.v1.CellAssignmentResponse\x12M\n" +
	"\x10ReportCellStatus\x12\x1b.swarm.v1.CellStatusRequest\x1a\x1c.swarm.v1.CellStatusResponse2\x8a\x03\n" +
	"\fGlobalRouter\x12A\n" +
	"\x06Submit\x12\x1a.swarm.v1.SubmitJobRequest\x1a\x1b.swarm.v1.SubmitJobResponse\x12S\n" +
	"\x0ePublishSummary\x12\x1f.swarm.v1.PublishSummaryRequest\x1a .swarm.v1.PublishSummaryResponse\x12J\n" +
	"\rGetGlobalView\x12\x1b.swarm.v1.GlobalViewRequest\x1a\x1c.swarm.v1.GlobalViewResponse\x12P\n" +
	"\rReportPartial\x12\x1e.swarm.v1.ReportPartialRequest\x1a\x1f.swarm.v1.ReportPartialResponse\x12D\n" +
	"\tJobStatus\x12\x1a.swarm.v1.JobStatusRequest\x1a\x1b.swarm.v1.JobStatusResponse2\xcb\x02\n" +
	"\n" +
	"CellLeader\x12G\n" +
	"\n" +
	"AssignWork\x12\x1b.swarm.v1.AssignWorkRequest\x1a\x1c.swarm.v1.AssignWorkResponse\x12G\n" +
	"\n" +
	"StepReport\x12\x1b.swarm.v1.StepReportRequest\x1a\x1c.swarm.v1.StepReportResponse\x12S\n" +
	"\x0eDeliverMessage\x12\x1f.swarm.v1.DeliverMessageRequest\x1a .swarm.v1.DeliverMessageResponse\x12V\n" +
	"\x0fMemberHeartbeat\x12 .swarm.v1.MemberHeartbeatRequest\x1a!.swarm.v1.MemberHeartbeatResponseB=Z;github.com/msivraj/swarm/internal/shell/transport;transportb\x06proto3"

var (
	file_swarm_proto_rawDescOnce sync.Once
	file_swarm_proto_rawDescData []byte
)

func file_swarm_proto_rawDescGZIP() []byte {
	file_swarm_proto_rawDescOnce.Do(func() {
		file_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)))
	})
	return file_swarm_proto_rawDescData
}

var file_swarm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_swarm_proto_goTypes = []any{
	(Coupling)(0),                   // 0: swarm.v1.Coupling
	(Health)(0),                     // 1: swarm.v1.Health
	(*SubmitJobRequest)(nil),        // 2: swarm.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),       // 3: swarm.v1.SubmitJobResponse
	(*JoinAgentRequest)(nil),        // 4: swarm.v1.JoinAgentRequest
	(*JoinAgentResponse)(nil),       // 5: swarm.v1.JoinAgentResponse
	(*CellAssignmentRequest)(nil),   // 6: swarm.v1.CellAssignmentRequest
	(*CellPeer)(nil),                // 7: swarm.v1.CellPeer
	(*CellAssignmentResponse)(nil),  // 8: swarm.v1.CellAssignmentResponse
	(*CellStatusRequest)(nil),       // 9: swarm.v1.CellStatusRequest
	(*CellStatusResponse)(nil),      // 10: swarm.v1.CellStatusResponse
	(*HeartbeatRequest)(nil),        // 11: swarm.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 12: swarm.v1.HeartbeatResponse
	(*Task)(nil),                    // 13: swarm.v1.Task
	(*PullTaskRequest)(nil),         // 14: swarm.v1.PullTaskRequest
	(*PullTaskResponse)(nil),        // 15: swarm.v1.PullTaskResponse
	(*ReportResultRequest)(nil),     // 16: swarm.v1.ReportResultRequest
	(*ReportResultResponse)(nil),    // 17: swarm.v1.ReportResultResponse
	(*PsRequest)(nil),               // 18: swarm.v1.PsRequest
	(*PsResponse)(nil),              // 19: swarm.v1.PsResponse
	(*JobStatusRequest)(nil),        // 20: swarm.v1.JobStatusRequest
	(*JobStatusResponse)(nil),       // 21: swarm.v1.JobStatusResponse
	(*JobSpec)(nil),                 // 22: swarm.v1.JobSpec
	(*RegionalSummary)(nil),         // 23: swarm.v1.RegionalSummary
	(*RegionView)(nil),              // 24: swarm.v1.RegionView
	(*PublishSummaryRequest)(nil),   // 25: swarm.v1.PublishSummaryRequest
	(*PublishSummaryResponse)(nil),  // 26: swarm.v1.PublishSummaryResponse
	(*GlobalViewRequest)(nil),       // 27: swarm.v1.GlobalViewRequest
	(*GlobalViewResponse)(nil),      // 28: swarm.v1.GlobalViewResponse
	(*DispatchTasksRequest)(nil),    // 29: swarm.v1.DispatchTasksRequest
	(*DispatchTasksResponse)(nil),   // 30: swarm.v1.DispatchTasksResponse
	(*PartialAggregate)(nil),        // 31: swarm.v1.PartialAggregate
	(*ReportPartialRequest)(nil),    // 32: swarm.v1.ReportPartialRequest
	(*ReportPartialResponse)(nil),   // 33: swarm.v1.ReportPartialResponse
	(*AssignWorkRequest)(nil),       // 34: swarm.v1.AssignWorkRequest
	(*AssignWorkResponse)(nil),      // 35: swarm.v1.AssignWorkResponse
	(*StepReportRequest)(nil),       // 36: swarm.v1.StepReportRequest
	(*StepReportResponse)(nil),      // 37: swarm.v1.StepReportResponse
	(*DeliverMessageRequest)(nil),   // 38: swarm.v1.DeliverMessageRequest
	(*DeliverMessageResponse)(nil),  // 39: swarm.v1.DeliverMessageResponse
	(*MemberHeartbeatRequest)(nil),  // 40: swarm.v1.MemberHeartbeatRequest
	(*MemberHeartbeatResponse)(nil), // 41: swarm.v1.MemberHeartbeatResponse
	nil,                             // 42: swarm.v1.SubmitJobRequest.ParamsEntry
	nil,                             // 43: swarm.v1.JobSpec.ParamsEntry
}
var file_swarm_proto_depIdxs = []int32{
	0,  // 0: swarm.v1.SubmitJobRequest.coupling:type_name -> swarm.v1.Coupling
	42, // 1: swarm.v1.SubmitJobRequest.params:type_name -> swarm.v1.SubmitJobRequest.ParamsEntry
	7,  // 2: swarm.v1.CellAssignmentResponse.peers:type_name -> swarm.v1.CellPeer
	13, // 3: swarm.v1.PullTaskResponse.task:type_name -> swarm.v1.Task
	0,  // 4: swarm.v1.JobSpec.coupling:type_name -> swarm.v1.Coupling
	43, // 5: swarm.v1.JobSpec.params:type_name -> swarm.v1.JobSpec.ParamsEntry
	1,  // 6: swarm.v1.RegionalSummary.health:type_name -> swarm.v1.Health
	1,  // 7: swarm.v1.RegionView.health:type_name -> swarm.v1.Health
	23, // 8: swarm.v1.PublishSummaryRequest.summary:type_name -> swarm.v1.RegionalSummary
	24, // 9: swarm.v1.GlobalViewResponse.regions:type_name -> swarm.v1.RegionView
	22, // 10: swarm.v1.DispatchTasksRequest.job:type_name -> swarm.v1.JobSpec
	13, // 11: swarm.v1.DispatchTasksRequest.tasks:type_name -> swarm.v1.Task
	31, // 12: swarm.v1.ReportPartialRequest.partial:type_name -> swarm.v1.PartialAggregate
	2,  // 13: swarm.v1.ControlPlane.SubmitJob:input_type -> swarm.v1.SubmitJobRequest
	4,  // 14: swarm.v1.ControlPlane.JoinAgent:input_type -> swarm.v1.JoinAgentRequest
	11, // 15: swarm.v1.ControlPlane.Heartbeat:input_type -> swarm.v1.HeartbeatRequest
	14, // 16: swarm.v1.ControlPlane.PullTask:input_type -> swarm.v1.PullTaskRequest
	16, // 17: swarm.v1.ControlPlane.ReportResult:input_type -> swarm.v1.ReportResultRequest
	18, // 18: swarm.v1.ControlPlane.Ps:input_type -> swarm.v1.PsRequest
	20, // 19: swarm.v1.ControlPlane.JobStatus:input_type -> swarm.v1.JobStatusRequest
	29, // 20: swarm.v1.ControlPlane.DispatchTasks:input_type -> swarm.v1.DispatchTasksRequest
	6,  // 21: swarm.v1.ControlPlane.CellAssignment:input_type -> swarm.v1.CellAssignmentRequest
	9,  // 22: swarm.v1.ControlPlane.ReportCellStatus:input_type -> swarm.v1.CellStatusRequest
	2,  // 23: swarm.v1.GlobalRouter.Submit:input_type -> swarm.v1.SubmitJobRequest
	25, // 24: swarm.v1.GlobalRouter.PublishSummary:input_type -> swarm.v1.PublishSummaryRequest
	27, // 25: swarm.v1.GlobalRouter.GetGlobalView:input_type -> swarm.v1.GlobalViewRequest
	32, // 26: swarm.v1.GlobalRouter.ReportPartial:input_type -> swarm.v1.ReportPartialRequest
	20, // 27: swarm.v1.GlobalRouter.JobStatus:input_type -> swarm.v1.JobStatusRequest
	34, // 28: swarm.v1.CellLeader.AssignWork:input_type -> swarm.v1.AssignWorkRequest
	36, // 29: swarm.v1.CellLeader.StepReport:input_type -> swarm.v1.StepReportRequest
	38, // 30: swarm.v1.CellLeader.DeliverMessage:input_type -> swarm.v1.DeliverMessageRequest
	40, // 31: swarm.v1.CellLeader.MemberHeartbeat:input_type -> swarm.v1.MemberHeartbeatRequest
	3,  // 32: swarm.v1.ControlPlane.SubmitJob:output_type -> swarm.v1.SubmitJobResponse
	5,  // 33: swarm.v1.ControlPlane.JoinAgent:output_type -> swarm.v1.JoinAgentResponse
	12, // 34: swarm.v1.ControlPlane.Heartbeat:output_type -> swarm.v1.HeartbeatResponse
	15, // 35: swarm.v1.ControlPlane.PullTask:output_type -> swarm.v1.PullTaskResponse
	17, // 36: swarm.v1.ControlPlane.ReportResult:output_type -> swarm.v1.ReportResultResponse
	19, // 37: swarm.v1.ControlPlane.Ps:output_type -> swarm.v1.PsResponse
	21, // 38: swarm.v1.ControlPlane.JobStatus:output_type -> swarm.v1.JobStatusResponse
	30, // 39: swarm.v1.ControlPlane.DispatchTasks:output_type -> swarm.v1.DispatchTasksResponse
	8,  // 40: swarm.v1.ControlPlane.CellAssignment:output_type -> swarm.v1.CellAssignmentResponse
	10, // 41: swarm.v1.ControlPlane.ReportCellStatus:output_type -> swarm.v1.CellStatusResponse
	3,  // 42: swarm.v1.GlobalRouter.Submit:output_type -> swarm.v1.SubmitJobResponse
	26, // 43: swarm.v1.GlobalRouter.PublishSummary:output_type -> swarm.v1.PublishSummaryResponse
	28, // 44: swarm.v1.GlobalRouter.GetGlobalView:output_type -> swarm.v1.GlobalViewResponse
	33, // 45: swarm.v1.GlobalRouter.ReportPartial:output_type -> swarm.v1.ReportPartialResponse
	21, // 46: swarm.v1.GlobalRouter.JobStatus:output_type -> swarm.v1.JobStatusResponse
	35, // 47: swarm.v1.CellLeader.AssignWork:output_type -> swarm.v1.AssignWorkResponse
	37, // 48: swarm.v1.CellLeader.StepReport:output_type -> swarm.v1.StepReportResponse
	39, // 49: swarm.v1.CellLeader.DeliverMessage:output_type -> swarm.v1.DeliverMessageResponse
	41, // 50: swarm.v1.CellLeader.MemberHeartbeat:output_type -> swarm.v1.MemberHeartbeatResponse
	32, // [32:51] is the sub-list for method output_type
	13, // [13:32] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_swarm_proto_init() }
func file_swarm_proto_init() {
	if File_swarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_swarm_proto_goTypes,
		DependencyIndexes: file_swarm_proto_depIdxs,
		EnumInfos:         file_swarm_proto_enumTypes,
		MessageInfos:      file_swarm_proto_msgTypes,
	}.Build()
	File_swarm_proto = out.File
	file_swarm_proto_goTypes = nil
	file_swarm_proto_depIdxs = nil
}
