// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: swarm.proto

package transport

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_SubmitJob_FullMethodName      = "/swarm.v1.ControlPlane/SubmitJob"
	ControlPlane_JoinAgent_FullMethodName      = "/swarm.v1.ControlPlane/JoinAgent"
	ControlPlane_Heartbeat_FullMethodName      = "/swarm.v1.ControlPlane/Heartbeat"
	ControlPlane_PullTask_FullMethodName       = "/swarm.v1.ControlPlane/PullTask"
	ControlPlane_ReportResult_FullMethodName   = "/swarm.v1.ControlPlane/ReportResult"
	ControlPlane_Ps_FullMethodName             = "/swarm.v1.ControlPlane/Ps"
	ControlPlane_JobStatus_FullMethodName      = "/swarm.v1.ControlPlane/JobStatus"
	ControlPlane_DispatchTasks_FullMethodName  = "/swarm.v1.ControlPlane/DispatchTasks"
	ControlPlane_CellAssignment_FullMethodName = "/swarm.v1.ControlPlane/CellAssignment"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane is the P0 control-plane surface: submit jobs, join agents,
// heartbeat, pull/report tasks, and query status. Single region, central
// membership (no gossip in P0).
type ControlPlaneClient interface {
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	JoinAgent(ctx context.Context, in *JoinAgentRequest, opts ...grpc.CallOption) (*JoinAgentResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	PullTask(ctx context.Context, in *PullTaskRequest, opts ...grpc.CallOption) (*PullTaskResponse, error)
	ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error)
	Ps(ctx context.Context, in *PsRequest, opts ...grpc.CallOption) (*PsResponse, error)
	JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
	// Cross-region task delivery: global->region (spread) and region->region (spill).
	DispatchTasks(ctx context.Context, in *DispatchTasksRequest, opts ...grpc.CallOption) (*DispatchTasksResponse, error)
	// A cell agent polls whether it belongs to a coupled cell and, if so, its
	// raft peer set + barrier shard (P2 coupled-cell activation).
	CellAssignment(ctx context.Context, in *CellAssignmentRequest, opts ...grpc.CallOption) (*CellAssignmentResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, ControlPlane_SubmitJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) JoinAgent(ctx context.Context, in *JoinAgentRequest, opts ...grpc.CallOption) (*JoinAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinAgentResponse)
	err := c.cc.Invoke(ctx, ControlPlane_JoinAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) PullTask(ctx context.Context, in *PullTaskRequest, opts ...grpc.CallOption) (*PullTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullTaskResponse)
	err := c.cc.Invoke(ctx, ControlPlane_PullTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReportResult(ctx context.Context, in *ReportResultRequest, opts ...grpc.CallOption) (*ReportResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportResultResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Ps(ctx context.Context, in *PsRequest, opts ...grpc.CallOption) (*PsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PsResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Ps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, ControlPlane_JobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) DispatchTasks(ctx context.Context, in *DispatchTasksRequest, opts ...grpc.CallOption) (*DispatchTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTasksResponse)
	err := c.cc.Invoke(ctx, ControlPlane_DispatchTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) CellAssignment(ctx context.Context, in *CellAssignmentRequest, opts ...grpc.CallOption) (*CellAssignmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CellAssignmentResponse)
	err := c.cc.Invoke(ctx, ControlPlane_CellAssignment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane is the P0 control-plane surface: submit jobs, join agents,
// heartbeat, pull/report tasks, and query status. Single region, central
// membership (no gossip in P0).
type ControlPlaneServer interface {
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	JoinAgent(context.Context, *JoinAgentRequest) (*JoinAgentResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	PullTask(context.Context, *PullTaskRequest) (*PullTaskResponse, error)
	ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error)
	Ps(context.Context, *PsRequest) (*PsResponse, error)
	JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error)
	// Cross-region task delivery: global->region (spread) and region->region (spill).
	DispatchTasks(context.Context, *DispatchTasksRequest) (*DispatchTasksResponse, error)
	// A cell agent polls whether it belongs to a coupled cell and, if so, its
	// raft peer set + barrier shard (P2 coupled-cell activation).
	CellAssignment(context.Context, *CellAssignmentRequest) (*CellAssignmentResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedControlPlaneServer) JoinAgent(context.Context, *JoinAgentRequest) (*JoinAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinAgent not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) PullTask(context.Context, *PullTaskRequest) (*PullTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullTask not implemented")
}
func (UnimplementedControlPlaneServer) ReportResult(context.Context, *ReportResultRequest) (*ReportResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedControlPlaneServer) Ps(context.Context, *PsRequest) (*PsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ps not implemented")
}
func (UnimplementedControlPlaneServer) JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobStatus not implemented")
}
func (UnimplementedControlPlaneServer) DispatchTasks(context.Context, *DispatchTasksRequest) (*DispatchTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTasks not implemented")
}
func (UnimplementedControlPlaneServer) CellAssignment(context.Context, *CellAssignmentRequest) (*CellAssignmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CellAssignment not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_SubmitJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_JoinAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).JoinAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_JoinAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).JoinAgent(ctx, req.(*JoinAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_PullTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).PullTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_PullTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).PullTask(ctx, req.(*PullTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportResult(ctx, req.(*ReportResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Ps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Ps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Ps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Ps(ctx, req.(*PsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_JobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).JobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_JobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).JobStatus(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_DispatchTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).DispatchTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_DispatchTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).DispatchTasks(ctx, req.(*DispatchTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_CellAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CellAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).CellAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_CellAssignment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).CellAssignment(ctx, req.(*CellAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitJob",
			Handler:    _ControlPlane_SubmitJob_Handler,
		},
		{
			MethodName: "JoinAgent",
			Handler:    _ControlPlane_JoinAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "PullTask",
			Handler:    _ControlPlane_PullTask_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _ControlPlane_ReportResult_Handler,
		},
		{
			MethodName: "Ps",
			Handler:    _ControlPlane_Ps_Handler,
		},
		{
			MethodName: "JobStatus",
			Handler:    _ControlPlane_JobStatus_Handler,
		},
		{
			MethodName: "DispatchTasks",
			Handler:    _ControlPlane_DispatchTasks_Handler,
		},
		{
			MethodName: "CellAssignment",
			Handler:    _ControlPlane_CellAssignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swarm.proto",
}

const (
	GlobalRouter_Submit_FullMethodName         = "/swarm.v1.GlobalRouter/Submit"
	GlobalRouter_PublishSummary_FullMethodName = "/swarm.v1.GlobalRouter/PublishSummary"
	GlobalRouter_GetGlobalView_FullMethodName  = "/swarm.v1.GlobalRouter/GetGlobalView"
	GlobalRouter_ReportPartial_FullMethodName  = "/swarm.v1.GlobalRouter/ReportPartial"
	GlobalRouter_JobStatus_FullMethodName      = "/swarm.v1.GlobalRouter/JobStatus"
)

// GlobalRouterClient is the client API for GlobalRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GlobalRouter is the P1 global routing layer (S3): it holds the merged
// GlobalView (routing.MergeGlobal), routes jobs (routing.Route), fans spread
// jobs across regions, and is the roll-up sink for their region partials.
type GlobalRouterClient interface {
	Submit(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
	PublishSummary(ctx context.Context, in *PublishSummaryRequest, opts ...grpc.CallOption) (*PublishSummaryResponse, error)
	GetGlobalView(ctx context.Context, in *GlobalViewRequest, opts ...grpc.CallOption) (*GlobalViewResponse, error)
	// Roll-up sink for Spread jobs: each participating region reports its region
	// PARTIAL here; the global layer combines them with aggregate.Merge.
	ReportPartial(ctx context.Context, in *ReportPartialRequest, opts ...grpc.CallOption) (*ReportPartialResponse, error)
	JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error)
}

type globalRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewGlobalRouterClient(cc grpc.ClientConnInterface) GlobalRouterClient {
	return &globalRouterClient{cc}
}

func (c *globalRouterClient) Submit(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, GlobalRouter_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalRouterClient) PublishSummary(ctx context.Context, in *PublishSummaryRequest, opts ...grpc.CallOption) (*PublishSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishSummaryResponse)
	err := c.cc.Invoke(ctx, GlobalRouter_PublishSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalRouterClient) GetGlobalView(ctx context.Context, in *GlobalViewRequest, opts ...grpc.CallOption) (*GlobalViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GlobalViewResponse)
	err := c.cc.Invoke(ctx, GlobalRouter_GetGlobalView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalRouterClient) ReportPartial(ctx context.Context, in *ReportPartialRequest, opts ...grpc.CallOption) (*ReportPartialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportPartialResponse)
	err := c.cc.Invoke(ctx, GlobalRouter_ReportPartial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *globalRouterClient) JobStatus(ctx context.Context, in *JobStatusRequest, opts ...grpc.CallOption) (*JobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusResponse)
	err := c.cc.Invoke(ctx, GlobalRouter_JobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlobalRouterServer is the server API for GlobalRouter service.
// All implementations must embed UnimplementedGlobalRouterServer
// for forward compatibility.
//
// GlobalRouter is the P1 global routing layer (S3): it holds the merged
// GlobalView (routing.MergeGlobal), routes jobs (routing.Route), fans spread
// jobs across regions, and is the roll-up sink for their region partials.
type GlobalRouterServer interface {
	Submit(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
	PublishSummary(context.Context, *PublishSummaryRequest) (*PublishSummaryResponse, error)
	GetGlobalView(context.Context, *GlobalViewRequest) (*GlobalViewResponse, error)
	// Roll-up sink for Spread jobs: each participating region reports its region
	// PARTIAL here; the global layer combines them with aggregate.Merge.
	ReportPartial(context.Context, *ReportPartialRequest) (*ReportPartialResponse, error)
	JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error)
	mustEmbedUnimplementedGlobalRouterServer()
}

// UnimplementedGlobalRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGlobalRouterServer struct{}

func (UnimplementedGlobalRouterServer) Submit(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedGlobalRouterServer) PublishSummary(context.Context, *PublishSummaryRequest) (*PublishSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSummary not implemented")
}
func (UnimplementedGlobalRouterServer) GetGlobalView(context.Context, *GlobalViewRequest) (*GlobalViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGlobalView not implemented")
}
func (UnimplementedGlobalRouterServer) ReportPartial(context.Context, *ReportPartialRequest) (*ReportPartialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPartial not implemented")
}
func (UnimplementedGlobalRouterServer) JobStatus(context.Context, *JobStatusRequest) (*JobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JobStatus not implemented")
}
func (UnimplementedGlobalRouterServer) mustEmbedUnimplementedGlobalRouterServer() {}
func (UnimplementedGlobalRouterServer) testEmbeddedByValue()                      {}

// UnsafeGlobalRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlobalRouterServer will
// result in compilation errors.
type UnsafeGlobalRouterServer interface {
	mustEmbedUnimplementedGlobalRouterServer()
}

func RegisterGlobalRouterServer(s grpc.ServiceRegistrar, srv GlobalRouterServer) {
	// If the following call panics, it indicates UnimplementedGlobalRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GlobalRouter_ServiceDesc, srv)
}

func _GlobalRouter_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalRouterServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlobalRouter_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalRouterServer).Submit(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalRouter_PublishSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalRouterServer).PublishSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlobalRouter_PublishSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalRouterServer).PublishSummary(ctx, req.(*PublishSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalRouter_GetGlobalView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GlobalViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalRouterServer).GetGlobalView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlobalRouter_GetGlobalView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalRouterServer).GetGlobalView(ctx, req.(*GlobalViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalRouter_ReportPartial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPartialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalRouterServer).ReportPartial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlobalRouter_ReportPartial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalRouterServer).ReportPartial(ctx, req.(*ReportPartialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GlobalRouter_JobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalRouterServer).JobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GlobalRouter_JobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalRouterServer).JobStatus(ctx, req.(*JobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GlobalRouter_ServiceDesc is the grpc.ServiceDesc for GlobalRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlobalRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.v1.GlobalRouter",
	HandlerType: (*GlobalRouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _GlobalRouter_Submit_Handler,
		},
		{
			MethodName: "PublishSummary",
			Handler:    _GlobalRouter_PublishSummary_Handler,
		},
		{
			MethodName: "GetGlobalView",
			Handler:    _GlobalRouter_GetGlobalView_Handler,
		},
		{
			MethodName: "ReportPartial",
			Handler:    _GlobalRouter_ReportPartial_Handler,
		},
		{
			MethodName: "JobStatus",
			Handler:    _GlobalRouter_JobStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swarm.proto",
}

const (
	CellLeader_AssignWork_FullMethodName      = "/swarm.v1.CellLeader/AssignWork"
	CellLeader_StepReport_FullMethodName      = "/swarm.v1.CellLeader/StepReport"
	CellLeader_DeliverMessage_FullMethodName  = "/swarm.v1.CellLeader/DeliverMessage"
	CellLeader_MemberHeartbeat_FullMethodName = "/swarm.v1.CellLeader/MemberHeartbeat"
)

// CellLeaderClient is the client API for CellLeader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CellLeader is the P2 per-cell coordination surface (leader <-> follower within
// one cell). Raft replication among leader candidates is handled INTERNALLY by
// hashicorp/raft in the leader shell and needs no hand-written proto here.
type CellLeaderClient interface {
	AssignWork(ctx context.Context, in *AssignWorkRequest, opts ...grpc.CallOption) (*AssignWorkResponse, error)
	StepReport(ctx context.Context, in *StepReportRequest, opts ...grpc.CallOption) (*StepReportResponse, error)
	DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error)
	MemberHeartbeat(ctx context.Context, in *MemberHeartbeatRequest, opts ...grpc.CallOption) (*MemberHeartbeatResponse, error)
}

type cellLeaderClient struct {
	cc grpc.ClientConnInterface
}

func NewCellLeaderClient(cc grpc.ClientConnInterface) CellLeaderClient {
	return &cellLeaderClient{cc}
}

func (c *cellLeaderClient) AssignWork(ctx context.Context, in *AssignWorkRequest, opts ...grpc.CallOption) (*AssignWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignWorkResponse)
	err := c.cc.Invoke(ctx, CellLeader_AssignWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellLeaderClient) StepReport(ctx context.Context, in *StepReportRequest, opts ...grpc.CallOption) (*StepReportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StepReportResponse)
	err := c.cc.Invoke(ctx, CellLeader_StepReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellLeaderClient) DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverMessageResponse)
	err := c.cc.Invoke(ctx, CellLeader_DeliverMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cellLeaderClient) MemberHeartbeat(ctx context.Context, in *MemberHeartbeatRequest, opts ...grpc.CallOption) (*MemberHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberHeartbeatResponse)
	err := c.cc.Invoke(ctx, CellLeader_MemberHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CellLeaderServer is the server API for CellLeader service.
// All implementations must embed UnimplementedCellLeaderServer
// for forward compatibility.
//
// CellLeader is the P2 per-cell coordination surface (leader <-> follower within
// one cell). Raft replication among leader candidates is handled INTERNALLY by
// hashicorp/raft in the leader shell and needs no hand-written proto here.
type CellLeaderServer interface {
	AssignWork(context.Context, *AssignWorkRequest) (*AssignWorkResponse, error)
	StepReport(context.Context, *StepReportRequest) (*StepReportResponse, error)
	DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error)
	MemberHeartbeat(context.Context, *MemberHeartbeatRequest) (*MemberHeartbeatResponse, error)
	mustEmbedUnimplementedCellLeaderServer()
}

// UnimplementedCellLeaderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCellLeaderServer struct{}

func (UnimplementedCellLeaderServer) AssignWork(context.Context, *AssignWorkRequest) (*AssignWorkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignWork not implemented")
}
func (UnimplementedCellLeaderServer) StepReport(context.Context, *StepReportRequest) (*StepReportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StepReport not implemented")
}
func (UnimplementedCellLeaderServer) DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedCellLeaderServer) MemberHeartbeat(context.Context, *MemberHeartbeatRequest) (*MemberHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MemberHeartbeat not implemented")
}
func (UnimplementedCellLeaderServer) mustEmbedUnimplementedCellLeaderServer() {}
func (UnimplementedCellLeaderServer) testEmbeddedByValue()                    {}

// UnsafeCellLeaderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CellLeaderServer will
// result in compilation errors.
type UnsafeCellLeaderServer interface {
	mustEmbedUnimplementedCellLeaderServer()
}

func RegisterCellLeaderServer(s grpc.ServiceRegistrar, srv CellLeaderServer) {
	// If the following call panics, it indicates UnimplementedCellLeaderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CellLeader_ServiceDesc, srv)
}

func _CellLeader_AssignWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellLeaderServer).AssignWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellLeader_AssignWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellLeaderServer).AssignWork(ctx, req.(*AssignWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellLeader_StepReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StepReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellLeaderServer).StepReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellLeader_StepReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellLeaderServer).StepReport(ctx, req.(*StepReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellLeader_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellLeaderServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellLeader_DeliverMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellLeaderServer).DeliverMessage(ctx, req.(*DeliverMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CellLeader_MemberHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CellLeaderServer).MemberHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CellLeader_MemberHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CellLeaderServer).MemberHeartbeat(ctx, req.(*MemberHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CellLeader_ServiceDesc is the grpc.ServiceDesc for CellLeader service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CellLeader_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.v1.CellLeader",
	HandlerType: (*CellLeaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignWork",
			Handler:    _CellLeader_AssignWork_Handler,
		},
		{
			MethodName: "StepReport",
			Handler:    _CellLeader_StepReport_Handler,
		},
		{
			MethodName: "DeliverMessage",
			Handler:    _CellLeader_DeliverMessage_Handler,
		},
		{
			MethodName: "MemberHeartbeat",
			Handler:    _CellLeader_MemberHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swarm.proto",
}
