// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: swarm.proto

package transport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Coupling int32

const (
	Coupling_COUPLING_INDEPENDENT     Coupling = 0
	Coupling_COUPLING_BARRIER         Coupling = 1
	Coupling_COUPLING_LEADER          Coupling = 2
	Coupling_COUPLING_MESSAGE_PASSING Coupling = 3
)

// Enum value maps for Coupling.
var (
	Coupling_name = map[int32]string{
		0: "COUPLING_INDEPENDENT",
		1: "COUPLING_BARRIER",
		2: "COUPLING_LEADER",
		3: "COUPLING_MESSAGE_PASSING",
	}
	Coupling_value = map[string]int32{
		"COUPLING_INDEPENDENT":     0,
		"COUPLING_BARRIER":         1,
		"COUPLING_LEADER":          2,
		"COUPLING_MESSAGE_PASSING": 3,
	}
)

func (x Coupling) Enum() *Coupling {
	p := new(Coupling)
	*p = x
	return p
}

func (x Coupling) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Coupling) Descriptor() protoreflect.EnumDescriptor {
	return file_swarm_proto_enumTypes[0].Descriptor()
}

func (Coupling) Type() protoreflect.EnumType {
	return &file_swarm_proto_enumTypes[0]
}

func (x Coupling) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Coupling.Descriptor instead.
func (Coupling) EnumDescriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Coupling      Coupling               `protobuf:"varint,2,opt,name=coupling,proto3,enum=swarm.v1.Coupling" json:"coupling,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *SubmitJobRequest) GetCoupling() Coupling {
	if x != nil {
		return x.Coupling
	}
	return Coupling_COUPLING_INDEPENDENT
}

func (x *SubmitJobRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JoinAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Caps          int32                  `protobuf:"varint,3,opt,name=caps,proto3" json:"caps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAgentRequest) Reset() {
	*x = JoinAgentRequest{}
	mi := &file_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAgentRequest) ProtoMessage() {}

func (x *JoinAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAgentRequest.ProtoReflect.Descriptor instead.
func (*JoinAgentRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *JoinAgentRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *JoinAgentRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *JoinAgentRequest) GetCaps() int32 {
	if x != nil {
		return x.Caps
	}
	return 0
}

type JoinAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CellId        string                 `protobuf:"bytes,1,opt,name=cell_id,json=cellId,proto3" json:"cell_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAgentResponse) Reset() {
	*x = JoinAgentResponse{}
	mi := &file_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAgentResponse) ProtoMessage() {}

func (x *JoinAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAgentResponse.ProtoReflect.Descriptor instead.
func (*JoinAgentResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *JoinAgentResponse) GetCellId() string {
	if x != nil {
		return x.CellId
	}
	return ""
}

func (x *JoinAgentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinAgentResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Task) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Task) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type PullTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         string                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTaskRequest) Reset() {
	*x = PullTaskRequest{}
	mi := &file_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskRequest) ProtoMessage() {}

func (x *PullTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskRequest.ProtoReflect.Descriptor instead.
func (*PullTaskRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *PullTaskRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type PullTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasTask       bool                   `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullTaskResponse) Reset() {
	*x = PullTaskResponse{}
	mi := &file_swarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullTaskResponse) ProtoMessage() {}

func (x *PullTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullTaskResponse.ProtoReflect.Descriptor instead.
func (*PullTaskResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{8}
}

func (x *PullTaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *PullTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ReportResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultRequest) Reset() {
	*x = ReportResultRequest{}
	mi := &file_swarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultRequest) ProtoMessage() {}

func (x *ReportResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultRequest.ProtoReflect.Descriptor instead.
func (*ReportResultRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{9}
}

func (x *ReportResultRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ReportResultRequest) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ReportResultRequest) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ReportResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResultResponse) Reset() {
	*x = ReportResultResponse{}
	mi := &file_swarm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResultResponse) ProtoMessage() {}

func (x *ReportResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResultResponse.ProtoReflect.Descriptor instead.
func (*ReportResultResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{10}
}

func (x *ReportResultResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type PsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsRequest) Reset() {
	*x = PsRequest{}
	mi := &file_swarm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsRequest) ProtoMessage() {}

func (x *PsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsRequest.ProtoReflect.Descriptor instead.
func (*PsRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{11}
}

type PsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         int32                  `protobuf:"varint,1,opt,name=cells,proto3" json:"cells,omitempty"`
	Machines      int32                  `protobuf:"varint,2,opt,name=machines,proto3" json:"machines,omitempty"`
	Jobs          int32                  `protobuf:"varint,3,opt,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PsResponse) Reset() {
	*x = PsResponse{}
	mi := &file_swarm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PsResponse) ProtoMessage() {}

func (x *PsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PsResponse.ProtoReflect.Descriptor instead.
func (*PsResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{12}
}

func (x *PsResponse) GetCells() int32 {
	if x != nil {
		return x.Cells
	}
	return 0
}

func (x *PsResponse) GetMachines() int32 {
	if x != nil {
		return x.Machines
	}
	return 0
}

func (x *PsResponse) GetJobs() int32 {
	if x != nil {
		return x.Jobs
	}
	return 0
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_swarm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{13}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Done          bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Aggregate     []byte                 `protobuf:"bytes,2,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_swarm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swarm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_swarm_proto_rawDescGZIP(), []int{14}
}

func (x *JobStatusResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *JobStatusResponse) GetAggregate() []byte {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

var File_swarm_proto protoreflect.FileDescriptor

const file_swarm_proto_rawDesc = "" +
	"\n" +
	"\vswarm.proto\x12\bswarm.v1\"\xd9\x01\n" +
	"\x10SubmitJobRequest\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12.\n" +
	"\bcoupling\x18\x02 \x01(\x0e2\x12.swarm.v1.CouplingR\bcoupling\x12>\n" +
	"\x06params\x18\x03 \x03(\v2&.swarm.v1.SubmitJobRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"T\n" +
	"\x10JoinAgentRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x12\n" +
	"\x04caps\x18\x03 \x01(\x05R\x04caps\"`\n" +
	"\x11JoinAgentResponse\x12\x17\n" +
	"\acell_id\x18\x01 \x01(\tR\x06cellId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"(\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"]\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\"'\n" +
	"\x0fPullTaskRequest\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\"Q\n" +
	"\x10PullTaskResponse\x12\x19\n" +
	"\bhas_task\x18\x01 \x01(\bR\ahasTask\x12\"\n" +
	"\x04task\x18\x02 \x01(\v2\x0e.swarm.v1.TaskR\x04task\"V\n" +
	"\x13ReportResultRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\"2\n" +
	"\x14ReportResultResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\v\n" +
	"\tPsRequest\"R\n" +
	"\n" +
	"PsResponse\x12\x14\n" +
	"\x05cells\x18\x01 \x01(\x05R\x05cells\x12\x1a\n" +
	"\bmachines\x18\x02 \x01(\x05R\bmachines\x12\x12\n" +
	"\x04jobs\x18\x03 \x01(\x05R\x04jobs\")\n" +
	"\x10JobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"E\n" +
	"\x11JobStatusResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12\x1c\n" +
	"\taggregate\x18\x02 \x01(\fR\taggregate*m\n" +
	"\bCoupling\x12\x18\n" +
	"\x14COUPLING_INDEPENDENT\x10\x00\x12\x14\n" +
	"\x10COUPLING_BARRIER\x10\x01\x12\x13\n" +
	"\x0fCOUPLING_LEADER\x10\x02\x12\x1c\n" +
	"\x18COUPLING_MESSAGE_PASSING\x10\x032\xe9\x03\n" +
	"\fControlPlane\x12D\n" +
	"\tSubmitJob\x12\x1a.swarm.v1.SubmitJobRequest\x1a\x1b.swarm.v1.SubmitJobResponse\x12D\n" +
	"\tJoinAgent\x12\x1a.swarm.v1.JoinAgentRequest\x1a\x1b.swarm.v1.JoinAgentResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.swarm.v1.HeartbeatRequest\x1a\x1b.swarm.v1.HeartbeatResponse\x12A\n" +
	"\bPullTask\x12\x19.swarm.v1.PullTaskRequest\x1a\x1a.swarm.v1.PullTaskResponse\x12M\n" +
	"\fReportResult\x12\x1d.swarm.v1.ReportResultRequest\x1a\x1e.swarm.v1.ReportResultResponse\x12/\n" +
	"\x02Ps\x12\x13.swarm.v1.PsRequest\x1a\x14.swarm.v1.PsResponse\x12D\n" +
	"\tJobStatus\x12\x1a.swarm.v1.JobStatusRequest\x1a\x1b.swarm.v1.JobStatusResponseB=Z;github.com/msivraj/swarm/internal/shell/transport;transportb\x06proto3"

var (
	file_swarm_proto_rawDescOnce sync.Once
	file_swarm_proto_rawDescData []byte
)

func file_swarm_proto_rawDescGZIP() []byte {
	file_swarm_proto_rawDescOnce.Do(func() {
		file_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)))
	})
	return file_swarm_proto_rawDescData
}

var file_swarm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_swarm_proto_goTypes = []any{
	(Coupling)(0),                // 0: swarm.v1.Coupling
	(*SubmitJobRequest)(nil),     // 1: swarm.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),    // 2: swarm.v1.SubmitJobResponse
	(*JoinAgentRequest)(nil),     // 3: swarm.v1.JoinAgentRequest
	(*JoinAgentResponse)(nil),    // 4: swarm.v1.JoinAgentResponse
	(*HeartbeatRequest)(nil),     // 5: swarm.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 6: swarm.v1.HeartbeatResponse
	(*Task)(nil),                 // 7: swarm.v1.Task
	(*PullTaskRequest)(nil),      // 8: swarm.v1.PullTaskRequest
	(*PullTaskResponse)(nil),     // 9: swarm.v1.PullTaskResponse
	(*ReportResultRequest)(nil),  // 10: swarm.v1.ReportResultRequest
	(*ReportResultResponse)(nil), // 11: swarm.v1.ReportResultResponse
	(*PsRequest)(nil),            // 12: swarm.v1.PsRequest
	(*PsResponse)(nil),           // 13: swarm.v1.PsResponse
	(*JobStatusRequest)(nil),     // 14: swarm.v1.JobStatusRequest
	(*JobStatusResponse)(nil),    // 15: swarm.v1.JobStatusResponse
	nil,                          // 16: swarm.v1.SubmitJobRequest.ParamsEntry
}
var file_swarm_proto_depIdxs = []int32{
	0,  // 0: swarm.v1.SubmitJobRequest.coupling:type_name -> swarm.v1.Coupling
	16, // 1: swarm.v1.SubmitJobRequest.params:type_name -> swarm.v1.SubmitJobRequest.ParamsEntry
	7,  // 2: swarm.v1.PullTaskResponse.task:type_name -> swarm.v1.Task
	1,  // 3: swarm.v1.ControlPlane.SubmitJob:input_type -> swarm.v1.SubmitJobRequest
	3,  // 4: swarm.v1.ControlPlane.JoinAgent:input_type -> swarm.v1.JoinAgentRequest
	5,  // 5: swarm.v1.ControlPlane.Heartbeat:input_type -> swarm.v1.HeartbeatRequest
	8,  // 6: swarm.v1.ControlPlane.PullTask:input_type -> swarm.v1.PullTaskRequest
	10, // 7: swarm.v1.ControlPlane.ReportResult:input_type -> swarm.v1.ReportResultRequest
	12, // 8: swarm.v1.ControlPlane.Ps:input_type -> swarm.v1.PsRequest
	14, // 9: swarm.v1.ControlPlane.JobStatus:input_type -> swarm.v1.JobStatusRequest
	2,  // 10: swarm.v1.ControlPlane.SubmitJob:output_type -> swarm.v1.SubmitJobResponse
	4,  // 11: swarm.v1.ControlPlane.JoinAgent:output_type -> swarm.v1.JoinAgentResponse
	6,  // 12: swarm.v1.ControlPlane.Heartbeat:output_type -> swarm.v1.HeartbeatResponse
	9,  // 13: swarm.v1.ControlPlane.PullTask:output_type -> swarm.v1.PullTaskResponse
	11, // 14: swarm.v1.ControlPlane.ReportResult:output_type -> swarm.v1.ReportResultResponse
	13, // 15: swarm.v1.ControlPlane.Ps:output_type -> swarm.v1.PsResponse
	15, // 16: swarm.v1.ControlPlane.JobStatus:output_type -> swarm.v1.JobStatusResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_swarm_proto_init() }
func file_swarm_proto_init() {
	if File_swarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swarm_proto_rawDesc), len(file_swarm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swarm_proto_goTypes,
		DependencyIndexes: file_swarm_proto_depIdxs,
		EnumInfos:         file_swarm_proto_enumTypes,
		MessageInfos:      file_swarm_proto_msgTypes,
	}.Build()
	File_swarm_proto = out.File
	file_swarm_proto_goTypes = nil
	file_swarm_proto_depIdxs = nil
}
